//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovementEIServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", ConfigurationName="MovementEIServiceReference.MovementService")]
    public interface MovementService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/GetAccountMovements", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<MovementEIServiceReference.GetAccountMovementsResponse> GetAccountMovementsAsync(MovementEIServiceReference.GetAccountMovementsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AccountMovementFilterIo : BaseFilterIo
    {
        
        private string accountNumberField;
        
        private string accountCurrencyCodeField;
        
        private System.DateTime periodFromField;
        
        private bool periodFromFieldSpecified;
        
        private System.DateTime periodToField;
        
        private bool periodToFieldSpecified;
        
        private string movementIdField;
        
        private System.DateTime lastMovementTimestampField;
        
        private bool lastMovementTimestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string accountCurrencyCode
        {
            get
            {
                return this.accountCurrencyCodeField;
            }
            set
            {
                this.accountCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime periodFrom
        {
            get
            {
                return this.periodFromField;
            }
            set
            {
                this.periodFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodFromSpecified
        {
            get
            {
                return this.periodFromFieldSpecified;
            }
            set
            {
                this.periodFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime periodTo
        {
            get
            {
                return this.periodToField;
            }
            set
            {
                this.periodToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodToSpecified
        {
            get
            {
                return this.periodToFieldSpecified;
            }
            set
            {
                this.periodToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string movementId
        {
            get
            {
                return this.movementIdField;
            }
            set
            {
                this.movementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime lastMovementTimestamp
        {
            get
            {
                return this.lastMovementTimestampField;
            }
            set
            {
                this.lastMovementTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastMovementTimestampSpecified
        {
            get
            {
                return this.lastMovementTimestampFieldSpecified;
            }
            set
            {
                this.lastMovementTimestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountMovementFilterIo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseFilterIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private AdditionalAttributeIo[] additionalAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalAttributes", Order=1)]
        public AdditionalAttributeIo[] additionalAttributes
        {
            get
            {
                return this.additionalAttributesField;
            }
            set
            {
                this.additionalAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BasePagerIo : AbstractIo
    {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int pageIndex
        {
            get
            {
                return this.pageIndexField;
            }
            set
            {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseFilterIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountMovementFilterIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePagerIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseQueryResultIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalAttributeIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoneyIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountMovementDetailIo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AbstractIo
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseQueryResultIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AdditionalAttributeIo : AbstractIo
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class MoneyIo : AbstractIo
    {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AccountMovementDetailIo : AbstractIo
    {
        
        private string movementIdField;
        
        private string paymentIdField;
        
        private string externalPaymentIdField;
        
        private int debitCreditField;
        
        private System.DateTime valueDateField;
        
        private string descriptionField;
        
        private MoneyIo amountField;
        
        private string accountNumberField;
        
        private string accountNameField;
        
        private string additionalInformationField;
        
        private System.DateTime documentDateField;
        
        private bool documentDateFieldSpecified;
        
        private string documentNumberField;
        
        private string partnerAccountNumberField;
        
        private string partnerNameField;
        
        private string partnerTaxCodeField;
        
        private string partnerBankCodeField;
        
        private string partnerBankField;
        
        private string intermediaryBankCodeField;
        
        private string intermediaryBankField;
        
        private string chargeDetailField;
        
        private string taxpayerCodeField;
        
        private string taxpayerNameField;
        
        private string treasuryCodeField;
        
        private string operationCodeField;
        
        private string additionalDescriptionField;
        
        private string exchangeRateField;
        
        private string partnerPersonalNumberField;
        
        private string partnerDocumentTypeField;
        
        private string partnerDocumentNumberField;
        
        private string parentExternalPaymentIdField;
        
        private string statusCodeField;
        
        private string transactionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string movementId
        {
            get
            {
                return this.movementIdField;
            }
            set
            {
                this.movementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string externalPaymentId
        {
            get
            {
                return this.externalPaymentIdField;
            }
            set
            {
                this.externalPaymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int debitCredit
        {
            get
            {
                return this.debitCreditField;
            }
            set
            {
                this.debitCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime valueDate
        {
            get
            {
                return this.valueDateField;
            }
            set
            {
                this.valueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public MoneyIo amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string accountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string additionalInformation
        {
            get
            {
                return this.additionalInformationField;
            }
            set
            {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime documentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentDateSpecified
        {
            get
            {
                return this.documentDateFieldSpecified;
            }
            set
            {
                this.documentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string documentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string partnerAccountNumber
        {
            get
            {
                return this.partnerAccountNumberField;
            }
            set
            {
                this.partnerAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string partnerName
        {
            get
            {
                return this.partnerNameField;
            }
            set
            {
                this.partnerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string partnerTaxCode
        {
            get
            {
                return this.partnerTaxCodeField;
            }
            set
            {
                this.partnerTaxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string partnerBankCode
        {
            get
            {
                return this.partnerBankCodeField;
            }
            set
            {
                this.partnerBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string partnerBank
        {
            get
            {
                return this.partnerBankField;
            }
            set
            {
                this.partnerBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string intermediaryBankCode
        {
            get
            {
                return this.intermediaryBankCodeField;
            }
            set
            {
                this.intermediaryBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string intermediaryBank
        {
            get
            {
                return this.intermediaryBankField;
            }
            set
            {
                this.intermediaryBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string chargeDetail
        {
            get
            {
                return this.chargeDetailField;
            }
            set
            {
                this.chargeDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string taxpayerCode
        {
            get
            {
                return this.taxpayerCodeField;
            }
            set
            {
                this.taxpayerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string taxpayerName
        {
            get
            {
                return this.taxpayerNameField;
            }
            set
            {
                this.taxpayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string treasuryCode
        {
            get
            {
                return this.treasuryCodeField;
            }
            set
            {
                this.treasuryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string operationCode
        {
            get
            {
                return this.operationCodeField;
            }
            set
            {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string additionalDescription
        {
            get
            {
                return this.additionalDescriptionField;
            }
            set
            {
                this.additionalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string exchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string partnerPersonalNumber
        {
            get
            {
                return this.partnerPersonalNumberField;
            }
            set
            {
                this.partnerPersonalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string partnerDocumentType
        {
            get
            {
                return this.partnerDocumentTypeField;
            }
            set
            {
                this.partnerDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string partnerDocumentNumber
        {
            get
            {
                return this.partnerDocumentNumberField;
            }
            set
            {
                this.partnerDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string parentExternalPaymentId
        {
            get
            {
                return this.parentExternalPaymentIdField;
            }
            set
            {
                this.parentExternalPaymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string transactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountMovementsRequestIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class GetAccountMovementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public MovementEIServiceReference.AccountMovementFilterIo accountMovementFilterIo;
        
        public GetAccountMovementsRequest()
        {
        }
        
        public GetAccountMovementsRequest(MovementEIServiceReference.AccountMovementFilterIo accountMovementFilterIo)
        {
            this.accountMovementFilterIo = accountMovementFilterIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountMovementsResponseIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class GetAccountMovementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public MovementEIServiceReference.BaseQueryResultIo result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("accountMovement")]
        public MovementEIServiceReference.AccountMovementDetailIo[] accountMovement;
        
        public GetAccountMovementsResponse()
        {
        }
        
        public GetAccountMovementsResponse(MovementEIServiceReference.BaseQueryResultIo result, MovementEIServiceReference.AccountMovementDetailIo[] accountMovement)
        {
            this.result = result;
            this.accountMovement = accountMovement;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MovementServiceChannel : MovementEIServiceReference.MovementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MovementServiceClient : System.ServiceModel.ClientBase<MovementEIServiceReference.MovementService>, MovementEIServiceReference.MovementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MovementServiceClient() : 
                base(MovementServiceClient.GetDefaultBinding(), MovementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MovementServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MovementServiceClient.GetBindingForEndpoint(endpointConfiguration), MovementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MovementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MovementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MovementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MovementEIServiceReference.GetAccountMovementsResponse> GetAccountMovementsAsync(MovementEIServiceReference.GetAccountMovementsRequest request)
        {
            return base.Channel.GetAccountMovementsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MovementServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MovementServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/dbi/dbiService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MovementServiceClient.GetBindingForEndpoint(EndpointConfiguration.MovementServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MovementServiceClient.GetEndpointAddress(EndpointConfiguration.MovementServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MovementServicePort,
        }
    }
}
