//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentEIServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", ConfigurationName="PaymentEIServiceReference.PaymentService")]
    public interface PaymentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/ImportSinglePaymentOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PaymentEIServiceReference.ImportSinglePaymentOrdersResponse> ImportSinglePaymentOrdersAsync(PaymentEIServiceReference.ImportSinglePaymentOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/ImportBatchPaymentOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PaymentEIServiceReference.ImportBatchPaymentOrderResponse> ImportBatchPaymentOrderAsync(PaymentEIServiceReference.ImportBatchPaymentOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/GetPaymentOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetPaymentOrderStatusResponse> GetPaymentOrderStatusAsync(PaymentEIServiceReference.GetPaymentOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/GetSinglePaymentId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetSinglePaymentIdResponse> GetSinglePaymentIdAsync(PaymentEIServiceReference.GetSinglePaymentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/GetBatchPaymentId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetBatchPaymentIdResponse> GetBatchPaymentIdAsync(PaymentEIServiceReference.GetBatchPaymentIdRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOtherBankForeignCurrencyPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOtherBankNationalCurrencyPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TreasuryTransferPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferWithinBankPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOwnAccountPaymentOrderIo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public abstract partial class PaymentOrderIo : AbstractIo
    {
        
        private long singlePaymentRequestIdField;
        
        private bool singlePaymentRequestIdFieldSpecified;
        
        private AccountIdentificationIo creditAccountField;
        
        private AccountIdentificationIo debitAccountField;
        
        private long documentNumberField;
        
        private bool documentNumberFieldSpecified;
        
        private MoneyIo amountField;
        
        private int positionField;
        
        private string additionalDescriptionField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long singlePaymentRequestId
        {
            get
            {
                return this.singlePaymentRequestIdField;
            }
            set
            {
                this.singlePaymentRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool singlePaymentRequestIdSpecified
        {
            get
            {
                return this.singlePaymentRequestIdFieldSpecified;
            }
            set
            {
                this.singlePaymentRequestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccountIdentificationIo creditAccount
        {
            get
            {
                return this.creditAccountField;
            }
            set
            {
                this.creditAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AccountIdentificationIo debitAccount
        {
            get
            {
                return this.debitAccountField;
            }
            set
            {
                this.debitAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long documentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentNumberSpecified
        {
            get
            {
                return this.documentNumberFieldSpecified;
            }
            set
            {
                this.documentNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MoneyIo amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string additionalDescription
        {
            get
            {
                return this.additionalDescriptionField;
            }
            set
            {
                this.additionalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AccountIdentificationIo : AbstractIo
    {
        
        private string accountNumberField;
        
        private string accountCurrencyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string accountCurrencyCode
        {
            get
            {
                return this.accountCurrencyCodeField;
            }
            set
            {
                this.accountCurrencyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseFilterIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePagerIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseQueryResultIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalAttributeIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentStatusDataIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentOrderResultIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoneyIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountIdentificationIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOtherBankForeignCurrencyPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOtherBankNationalCurrencyPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TreasuryTransferPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferWithinBankPaymentOrderIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferToOwnAccountPaymentOrderIo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AbstractIo
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseFilterIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private AdditionalAttributeIo[] additionalAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalAttributes", Order=1)]
        public AdditionalAttributeIo[] additionalAttributes
        {
            get
            {
                return this.additionalAttributesField;
            }
            set
            {
                this.additionalAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BasePagerIo : AbstractIo
    {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int pageIndex
        {
            get
            {
                return this.pageIndexField;
            }
            set
            {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AdditionalAttributeIo : AbstractIo
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseQueryResultIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class PaymentStatusDataIo : AbstractIo
    {
        
        private int positionField;
        
        private bool positionFieldSpecified;
        
        private string paymentIdField;
        
        private string paymentStatusField;
        
        private string errorDetailENField;
        
        private string errorDetailGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string paymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string errorDetailEN
        {
            get
            {
                return this.errorDetailENField;
            }
            set
            {
                this.errorDetailENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string errorDetailGE
        {
            get
            {
                return this.errorDetailGEField;
            }
            set
            {
                this.errorDetailGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class PaymentOrderResultIo : AbstractIo
    {
        
        private int positionField;
        
        private long paymentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class MoneyIo : AbstractIo
    {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class TransferToOtherBankForeignCurrencyPaymentOrderIo : PaymentOrderIo
    {
        
        private string beneficiaryNameField;
        
        private string beneficiaryAddressField;
        
        private string beneficiaryBankCodeField;
        
        private string beneficiaryBankNameField;
        
        private string intermediaryBankCodeField;
        
        private string intermediaryBankNameField;
        
        private string chargeDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string beneficiaryName
        {
            get
            {
                return this.beneficiaryNameField;
            }
            set
            {
                this.beneficiaryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string beneficiaryAddress
        {
            get
            {
                return this.beneficiaryAddressField;
            }
            set
            {
                this.beneficiaryAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string beneficiaryBankCode
        {
            get
            {
                return this.beneficiaryBankCodeField;
            }
            set
            {
                this.beneficiaryBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string beneficiaryBankName
        {
            get
            {
                return this.beneficiaryBankNameField;
            }
            set
            {
                this.beneficiaryBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string intermediaryBankCode
        {
            get
            {
                return this.intermediaryBankCodeField;
            }
            set
            {
                this.intermediaryBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string intermediaryBankName
        {
            get
            {
                return this.intermediaryBankNameField;
            }
            set
            {
                this.intermediaryBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string chargeDetails
        {
            get
            {
                return this.chargeDetailsField;
            }
            set
            {
                this.chargeDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class TransferToOtherBankNationalCurrencyPaymentOrderIo : PaymentOrderIo
    {
        
        private string beneficiaryNameField;
        
        private string beneficiaryTaxCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string beneficiaryName
        {
            get
            {
                return this.beneficiaryNameField;
            }
            set
            {
                this.beneficiaryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string beneficiaryTaxCode
        {
            get
            {
                return this.beneficiaryTaxCodeField;
            }
            set
            {
                this.beneficiaryTaxCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class TreasuryTransferPaymentOrderIo : PaymentOrderIo
    {
        
        private string taxpayerCodeField;
        
        private string taxpayerNameField;
        
        private string treasuryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taxpayerCode
        {
            get
            {
                return this.taxpayerCodeField;
            }
            set
            {
                this.taxpayerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string taxpayerName
        {
            get
            {
                return this.taxpayerNameField;
            }
            set
            {
                this.taxpayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string treasuryCode
        {
            get
            {
                return this.treasuryCodeField;
            }
            set
            {
                this.treasuryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class TransferWithinBankPaymentOrderIo : PaymentOrderIo
    {
        
        private string beneficiaryNameField;
        
        private string beneficiaryTaxCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string beneficiaryName
        {
            get
            {
                return this.beneficiaryNameField;
            }
            set
            {
                this.beneficiaryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string beneficiaryTaxCode
        {
            get
            {
                return this.beneficiaryTaxCodeField;
            }
            set
            {
                this.beneficiaryTaxCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class TransferToOwnAccountPaymentOrderIo : PaymentOrderIo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportSinglePaymentOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("singlePaymentOrder", IsNullable=false)]
        public PaymentEIServiceReference.PaymentOrderIo[] ImportSinglePaymentOrdersRequestIo;
        
        public ImportSinglePaymentOrdersRequest()
        {
        }
        
        public ImportSinglePaymentOrdersRequest(PaymentEIServiceReference.PaymentOrderIo[] ImportSinglePaymentOrdersRequestIo)
        {
            this.ImportSinglePaymentOrdersRequestIo = ImportSinglePaymentOrdersRequestIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportSinglePaymentOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PaymentOrdersResults", IsNullable=false)]
        public PaymentEIServiceReference.PaymentOrderResultIo[] ImportSinglePaymentOrdersResponseIo;
        
        public ImportSinglePaymentOrdersResponse()
        {
        }
        
        public ImportSinglePaymentOrdersResponse(PaymentEIServiceReference.PaymentOrderResultIo[] ImportSinglePaymentOrdersResponseIo)
        {
            this.ImportSinglePaymentOrdersResponseIo = ImportSinglePaymentOrdersResponseIo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class ImportBatchPaymentOrderRequestIo : AbstractIo
    {
        
        private string batchPaymentRequestIdField;
        
        private AccountIdentificationIo debitAccountIdentificationField;
        
        private string batchNameField;
        
        private PaymentOrderIo[] paymentOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string batchPaymentRequestId
        {
            get
            {
                return this.batchPaymentRequestIdField;
            }
            set
            {
                this.batchPaymentRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccountIdentificationIo debitAccountIdentification
        {
            get
            {
                return this.debitAccountIdentificationField;
            }
            set
            {
                this.debitAccountIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string batchName
        {
            get
            {
                return this.batchNameField;
            }
            set
            {
                this.batchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentOrder", Order=3)]
        public PaymentOrderIo[] paymentOrder
        {
            get
            {
                return this.paymentOrderField;
            }
            set
            {
                this.paymentOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class ImportBatchPaymentOrderResponseIo
    {
        
        private long mygeminiBatchIdField;
        
        private bool mygeminiBatchIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mygeminiBatchId
        {
            get
            {
                return this.mygeminiBatchIdField;
            }
            set
            {
                this.mygeminiBatchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mygeminiBatchIdSpecified
        {
            get
            {
                return this.mygeminiBatchIdFieldSpecified;
            }
            set
            {
                this.mygeminiBatchIdFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportBatchPaymentOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.ImportBatchPaymentOrderRequestIo ImportBatchPaymentOrderRequestIo;
        
        public ImportBatchPaymentOrderRequest()
        {
        }
        
        public ImportBatchPaymentOrderRequest(PaymentEIServiceReference.ImportBatchPaymentOrderRequestIo ImportBatchPaymentOrderRequestIo)
        {
            this.ImportBatchPaymentOrderRequestIo = ImportBatchPaymentOrderRequestIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportBatchPaymentOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.ImportBatchPaymentOrderResponseIo ImportBatchPaymentOrderResponseIo;
        
        public ImportBatchPaymentOrderResponse()
        {
        }
        
        public ImportBatchPaymentOrderResponse(PaymentEIServiceReference.ImportBatchPaymentOrderResponseIo ImportBatchPaymentOrderResponseIo)
        {
            this.ImportBatchPaymentOrderResponseIo = ImportBatchPaymentOrderResponseIo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetPaymentOrderStatusRequestIo
    {
        
        private long singlePaymentIdField;
        
        private bool singlePaymentIdFieldSpecified;
        
        private long batchPaymentIdField;
        
        private bool batchPaymentIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long singlePaymentId
        {
            get
            {
                return this.singlePaymentIdField;
            }
            set
            {
                this.singlePaymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool singlePaymentIdSpecified
        {
            get
            {
                return this.singlePaymentIdFieldSpecified;
            }
            set
            {
                this.singlePaymentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long batchPaymentId
        {
            get
            {
                return this.batchPaymentIdField;
            }
            set
            {
                this.batchPaymentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchPaymentIdSpecified
        {
            get
            {
                return this.batchPaymentIdFieldSpecified;
            }
            set
            {
                this.batchPaymentIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetPaymentOrderStatusResponseIo
    {
        
        private string statusField;
        
        private PaymentStatusDataIo singlePaymentDataField;
        
        private PaymentStatusDataIo[] batchPaymentDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaymentStatusDataIo singlePaymentData
        {
            get
            {
                return this.singlePaymentDataField;
            }
            set
            {
                this.singlePaymentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("batchPaymentData", Order=2)]
        public PaymentStatusDataIo[] batchPaymentData
        {
            get
            {
                return this.batchPaymentDataField;
            }
            set
            {
                this.batchPaymentDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentOrderStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetPaymentOrderStatusRequestIo GetPaymentOrderStatusRequestIo;
        
        public GetPaymentOrderStatusRequest()
        {
        }
        
        public GetPaymentOrderStatusRequest(PaymentEIServiceReference.GetPaymentOrderStatusRequestIo GetPaymentOrderStatusRequestIo)
        {
            this.GetPaymentOrderStatusRequestIo = GetPaymentOrderStatusRequestIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentOrderStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetPaymentOrderStatusResponseIo GetPaymentOrderStatusResponseIo;
        
        public GetPaymentOrderStatusResponse()
        {
        }
        
        public GetPaymentOrderStatusResponse(PaymentEIServiceReference.GetPaymentOrderStatusResponseIo GetPaymentOrderStatusResponseIo)
        {
            this.GetPaymentOrderStatusResponseIo = GetPaymentOrderStatusResponseIo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetSinglePaymentIdRequestIo
    {
        
        private long singlePaymentRequestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long singlePaymentRequestId
        {
            get
            {
                return this.singlePaymentRequestIdField;
            }
            set
            {
                this.singlePaymentRequestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetSinglePaymentIdResponseIo
    {
        
        private long paymentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinglePaymentIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetSinglePaymentIdRequestIo GetSinglePaymentIdRequestIo;
        
        public GetSinglePaymentIdRequest()
        {
        }
        
        public GetSinglePaymentIdRequest(PaymentEIServiceReference.GetSinglePaymentIdRequestIo GetSinglePaymentIdRequestIo)
        {
            this.GetSinglePaymentIdRequestIo = GetSinglePaymentIdRequestIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinglePaymentIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetSinglePaymentIdResponseIo GetSinglePaymentIdResponseIo;
        
        public GetSinglePaymentIdResponse()
        {
        }
        
        public GetSinglePaymentIdResponse(PaymentEIServiceReference.GetSinglePaymentIdResponseIo GetSinglePaymentIdResponseIo)
        {
            this.GetSinglePaymentIdResponseIo = GetSinglePaymentIdResponseIo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetBatchPaymentIdRequestIo
    {
        
        private long batchPaymentRequestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long batchPaymentRequestId
        {
            get
            {
                return this.batchPaymentRequestIdField;
            }
            set
            {
                this.batchPaymentRequestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class GetBatchPaymentIdResponseIo
    {
        
        private long batchIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBatchPaymentIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetBatchPaymentIdRequestIo GetBatchPaymentIdRequestIo;
        
        public GetBatchPaymentIdRequest()
        {
        }
        
        public GetBatchPaymentIdRequest(PaymentEIServiceReference.GetBatchPaymentIdRequestIo GetBatchPaymentIdRequestIo)
        {
            this.GetBatchPaymentIdRequestIo = GetBatchPaymentIdRequestIo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBatchPaymentIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public PaymentEIServiceReference.GetBatchPaymentIdResponseIo GetBatchPaymentIdResponseIo;
        
        public GetBatchPaymentIdResponse()
        {
        }
        
        public GetBatchPaymentIdResponse(PaymentEIServiceReference.GetBatchPaymentIdResponseIo GetBatchPaymentIdResponseIo)
        {
            this.GetBatchPaymentIdResponseIo = GetBatchPaymentIdResponseIo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PaymentServiceChannel : PaymentEIServiceReference.PaymentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<PaymentEIServiceReference.PaymentService>, PaymentEIServiceReference.PaymentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentServiceClient() : 
                base(PaymentServiceClient.GetDefaultBinding(), PaymentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PaymentServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), PaymentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentEIServiceReference.ImportSinglePaymentOrdersResponse> PaymentEIServiceReference.PaymentService.ImportSinglePaymentOrdersAsync(PaymentEIServiceReference.ImportSinglePaymentOrdersRequest request)
        {
            return base.Channel.ImportSinglePaymentOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentEIServiceReference.ImportSinglePaymentOrdersResponse> ImportSinglePaymentOrdersAsync(PaymentEIServiceReference.PaymentOrderIo[] ImportSinglePaymentOrdersRequestIo)
        {
            PaymentEIServiceReference.ImportSinglePaymentOrdersRequest inValue = new PaymentEIServiceReference.ImportSinglePaymentOrdersRequest();
            inValue.ImportSinglePaymentOrdersRequestIo = ImportSinglePaymentOrdersRequestIo;
            return ((PaymentEIServiceReference.PaymentService)(this)).ImportSinglePaymentOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentEIServiceReference.ImportBatchPaymentOrderResponse> PaymentEIServiceReference.PaymentService.ImportBatchPaymentOrderAsync(PaymentEIServiceReference.ImportBatchPaymentOrderRequest request)
        {
            return base.Channel.ImportBatchPaymentOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentEIServiceReference.ImportBatchPaymentOrderResponse> ImportBatchPaymentOrderAsync(PaymentEIServiceReference.ImportBatchPaymentOrderRequestIo ImportBatchPaymentOrderRequestIo)
        {
            PaymentEIServiceReference.ImportBatchPaymentOrderRequest inValue = new PaymentEIServiceReference.ImportBatchPaymentOrderRequest();
            inValue.ImportBatchPaymentOrderRequestIo = ImportBatchPaymentOrderRequestIo;
            return ((PaymentEIServiceReference.PaymentService)(this)).ImportBatchPaymentOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetPaymentOrderStatusResponse> PaymentEIServiceReference.PaymentService.GetPaymentOrderStatusAsync(PaymentEIServiceReference.GetPaymentOrderStatusRequest request)
        {
            return base.Channel.GetPaymentOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentEIServiceReference.GetPaymentOrderStatusResponse> GetPaymentOrderStatusAsync(PaymentEIServiceReference.GetPaymentOrderStatusRequestIo GetPaymentOrderStatusRequestIo)
        {
            PaymentEIServiceReference.GetPaymentOrderStatusRequest inValue = new PaymentEIServiceReference.GetPaymentOrderStatusRequest();
            inValue.GetPaymentOrderStatusRequestIo = GetPaymentOrderStatusRequestIo;
            return ((PaymentEIServiceReference.PaymentService)(this)).GetPaymentOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetSinglePaymentIdResponse> PaymentEIServiceReference.PaymentService.GetSinglePaymentIdAsync(PaymentEIServiceReference.GetSinglePaymentIdRequest request)
        {
            return base.Channel.GetSinglePaymentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentEIServiceReference.GetSinglePaymentIdResponse> GetSinglePaymentIdAsync(PaymentEIServiceReference.GetSinglePaymentIdRequestIo GetSinglePaymentIdRequestIo)
        {
            PaymentEIServiceReference.GetSinglePaymentIdRequest inValue = new PaymentEIServiceReference.GetSinglePaymentIdRequest();
            inValue.GetSinglePaymentIdRequestIo = GetSinglePaymentIdRequestIo;
            return ((PaymentEIServiceReference.PaymentService)(this)).GetSinglePaymentIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaymentEIServiceReference.GetBatchPaymentIdResponse> PaymentEIServiceReference.PaymentService.GetBatchPaymentIdAsync(PaymentEIServiceReference.GetBatchPaymentIdRequest request)
        {
            return base.Channel.GetBatchPaymentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaymentEIServiceReference.GetBatchPaymentIdResponse> GetBatchPaymentIdAsync(PaymentEIServiceReference.GetBatchPaymentIdRequestIo GetBatchPaymentIdRequestIo)
        {
            PaymentEIServiceReference.GetBatchPaymentIdRequest inValue = new PaymentEIServiceReference.GetBatchPaymentIdRequest();
            inValue.GetBatchPaymentIdRequestIo = GetBatchPaymentIdRequestIo;
            return ((PaymentEIServiceReference.PaymentService)(this)).GetBatchPaymentIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/csi/dbiService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentServiceClient.GetBindingForEndpoint(EndpointConfiguration.PaymentServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentServiceClient.GetEndpointAddress(EndpointConfiguration.PaymentServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            PaymentServicePort,
        }
    }
}
