//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostboxEIServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", ConfigurationName="PostboxEIServiceReference.PostboxService")]
    public interface PostboxService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/GetMessagesFromPostbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PostboxEIServiceReference.GetMessagesFromPostboxResponse> GetMessagesFromPostboxAsync(PostboxEIServiceReference.GetMessagesFromPostboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mygemini.com/schemas/mygemini/AcknowledgePostboxMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractIo))]
        System.Threading.Tasks.Task<PostboxEIServiceReference.AcknowledgePostboxMessagesResponse> AcknowledgePostboxMessagesAsync(PostboxEIServiceReference.AcknowledgePostboxMessagesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class PostboxMessageIo : AbstractIo
    {
        
        private long messageIdField;
        
        private string messageTextField;
        
        private string messageTypeField;
        
        private string messageStatusField;
        
        private AdditionalAttributeIo[] additionalAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string messageText
        {
            get
            {
                return this.messageTextField;
            }
            set
            {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string messageStatus
        {
            get
            {
                return this.messageStatusField;
            }
            set
            {
                this.messageStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalAttributes", Order=4)]
        public AdditionalAttributeIo[] additionalAttributes
        {
            get
            {
                return this.additionalAttributesField;
            }
            set
            {
                this.additionalAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AdditionalAttributeIo : AbstractIo
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseFilterIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePagerIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseQueryResultIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoneyIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalAttributeIo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostboxMessageIo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class AbstractIo
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseFilterIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private AdditionalAttributeIo[] additionalAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalAttributes", Order=1)]
        public AdditionalAttributeIo[] additionalAttributes
        {
            get
            {
                return this.additionalAttributesField;
            }
            set
            {
                this.additionalAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BasePagerIo : AbstractIo
    {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int pageIndex
        {
            get
            {
                return this.pageIndexField;
            }
            set
            {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class BaseQueryResultIo : AbstractIo
    {
        
        private BasePagerIo pagerField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BasePagerIo pager
        {
            get
            {
                return this.pagerField;
            }
            set
            {
                this.pagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mygemini.com/schemas/mygemini")]
    public partial class MoneyIo : AbstractIo
    {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPostboxMessagesRequestIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class GetMessagesFromPostboxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public string messageType;
        
        public GetMessagesFromPostboxRequest()
        {
        }
        
        public GetMessagesFromPostboxRequest(string messageType)
        {
            this.messageType = messageType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPostboxMessagesResponseIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class GetMessagesFromPostboxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public PostboxEIServiceReference.PostboxMessageIo[] messages;
        
        public GetMessagesFromPostboxResponse()
        {
        }
        
        public GetMessagesFromPostboxResponse(PostboxEIServiceReference.PostboxMessageIo[] messages)
        {
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostboxAcknowledgementRequestIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class AcknowledgePostboxMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("messageIds")]
        public long[] messageIds;
        
        public AcknowledgePostboxMessagesRequest()
        {
        }
        
        public AcknowledgePostboxMessagesRequest(long[] messageIds)
        {
            this.messageIds = messageIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostboxAcknowledgementResponseIo", WrapperNamespace="http://www.mygemini.com/schemas/mygemini", IsWrapped=true)]
    public partial class AcknowledgePostboxMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mygemini.com/schemas/mygemini", Order=0)]
        public string responseText;
        
        public AcknowledgePostboxMessagesResponse()
        {
        }
        
        public AcknowledgePostboxMessagesResponse(string responseText)
        {
            this.responseText = responseText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PostboxServiceChannel : PostboxEIServiceReference.PostboxService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PostboxServiceClient : System.ServiceModel.ClientBase<PostboxEIServiceReference.PostboxService>, PostboxEIServiceReference.PostboxService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PostboxServiceClient() : 
                base(PostboxServiceClient.GetDefaultBinding(), PostboxServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PostboxServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostboxServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PostboxServiceClient.GetBindingForEndpoint(endpointConfiguration), PostboxServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostboxServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PostboxServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostboxServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PostboxServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostboxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostboxEIServiceReference.GetMessagesFromPostboxResponse> PostboxEIServiceReference.PostboxService.GetMessagesFromPostboxAsync(PostboxEIServiceReference.GetMessagesFromPostboxRequest request)
        {
            return base.Channel.GetMessagesFromPostboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostboxEIServiceReference.GetMessagesFromPostboxResponse> GetMessagesFromPostboxAsync(string messageType)
        {
            PostboxEIServiceReference.GetMessagesFromPostboxRequest inValue = new PostboxEIServiceReference.GetMessagesFromPostboxRequest();
            inValue.messageType = messageType;
            return ((PostboxEIServiceReference.PostboxService)(this)).GetMessagesFromPostboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PostboxEIServiceReference.AcknowledgePostboxMessagesResponse> PostboxEIServiceReference.PostboxService.AcknowledgePostboxMessagesAsync(PostboxEIServiceReference.AcknowledgePostboxMessagesRequest request)
        {
            return base.Channel.AcknowledgePostboxMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PostboxEIServiceReference.AcknowledgePostboxMessagesResponse> AcknowledgePostboxMessagesAsync(long[] messageIds)
        {
            PostboxEIServiceReference.AcknowledgePostboxMessagesRequest inValue = new PostboxEIServiceReference.AcknowledgePostboxMessagesRequest();
            inValue.messageIds = messageIds;
            return ((PostboxEIServiceReference.PostboxService)(this)).AcknowledgePostboxMessagesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PostboxServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PostboxServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/dbi/dbiService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PostboxServiceClient.GetBindingForEndpoint(EndpointConfiguration.PostboxServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PostboxServiceClient.GetEndpointAddress(EndpointConfiguration.PostboxServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            PostboxServicePort,
        }
    }
}
